wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.16.2
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707837095.641924
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.9.7
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
